#ifndef __ERROR_TYPE_HPP__
#define __ERROR_TYPE_HPP__

enum ErrorType {
    ERR_UNTERMINATED_STRING = 0,
    ERR_UNEXPECTED_TOKEN = 1,
    ERR_UNTERMINATED_MULTILINE_STRING = 2,
    ERR_NON_CHAR_VALUE_INSIDE_CHAR = 3,
    ERR_CHAR_LONGER_THAN_SINGLE_CHARACTER = 4,
    ERR_EXPECTED_PATH_AFTER_USE = 5,
    ERR_UNEXPECTED_DEFINITION = 6,
    ERR_NO_BODY_DECLARED = 7,
    ERR_USE_STATEMENT_MUST_BE_AT_TOP_LEVEL = 8,
    ERR_CONSTRUCTOR_NAME_DOES_NOT_MATCH_DATA_NAME = 9,
    ERR_CAN_ONLY_EXTEND_FROM_SINGLE_ERROR_SET = 10,
};

#endif
